language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install psutil six
  - ./scripts/install_frameworks.sh
  - python setup.py develop
env:
  - DJANGO_VERSION=1.11.29
  - DJANGO_VERSION=2.2.11
  - DJANGO_VERSION=3.0.4
  - FLASK_VERSION=1.0.4
  - FLASK_VERSION=1.1.1
matrix:
  exclude:
    - python: 2.7
      env: DJANGO_VERSION=2.2.11
    - python: 2.7
      env: DJANGO_VERSION=3.0.4
    - python: 3.4
      env: DJANGO_VERSION=2.2.11
    - python: 3.4
      env: DJANGO_VERSION=3.0.4
    - python: 3.4
      env: FLASK_VERSION=1.1.1
    - python: 3.5
      env: DJANGO_VERSION=3.0.4
script: python setup.py test
notifications:
  slack:
    secure: A6A3o/F3VyRnmhL2/9QXkXTi70ZwJIUQGts9BWPfgkiBBDATKe7OijZms+b0xFUrJ2DKHyHocLBf4IVnoFihwyQy05vv3fOjpJlBtRaRifsgFh8gQw1hQ+1LENJQj0QUk+kEJLAtZ3PY/KyTBZUeSo/ZruMmTQAWmpUAKypIzkUTjjdE+Kh0w9VYaUfOgd2fmSXetCda/FvKEob1eAhjYTvAgfp8U4yS+SrHwvDnxLNwStZdfIKssuES8CiA/u7gzNdZphQS8A5XC+FWfz3sXSCcqG6Cp62NPhorEYXpUalzZ40pgTI6aDkcvmuT+ke+B5RGDpVYgx2mBlqPzgynosd20DlRgrN4rUE6vn8YSi6Lny1TmZURGFgckioBU5C/JCEbgKIADSQ+ZZ2YdDQ0SSduDqBi4wdxapDMCAyLAVyZga5Uxjxuc4gy1UHfGhpbXYrg0WYkmqkp6Z5ocz77LCD4fBIox27ng1e3ZeV+m6W7Z2HffvRlwndaXnkvfcSQF+6zjnhNnbrImUvshbDGSCM4jGMlQReajs5yL+qws5ePnGa2h/2Fq/FfpiqS1wCK3sEcRdk9FjMstC8REpThuFiK8z/FRTtdhHx4tiQW3MVCQayhN/yIxTKxYPh8Md7yg0N/Qahtifb4mvl+cvHfM1G9Ksnx4X1SlE19JS9tTmU=
